version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: bank_postgres
    restart: always
    environment:
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
      POSTGRES_DB: bank_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: bank_api
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: >
      sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      node dist/src/main.js
      "

volumes:
  postgres_data:
